/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/Dashboard/Dashboard': RouteRecordInfo<'/Dashboard/Dashboard', '/Dashboard/Dashboard', Record<never, never>, Record<never, never>>,
    '/MenuTemplate': RouteRecordInfo<'/MenuTemplate', '/MenuTemplate', Record<never, never>, Record<never, never>>,
    '/Project/NewProject': RouteRecordInfo<'/Project/NewProject', '/Project/NewProject', Record<never, never>, Record<never, never>>,
    '/Project/ProjectDetails': RouteRecordInfo<'/Project/ProjectDetails', '/Project/ProjectDetails', Record<never, never>, Record<never, never>>,
    '/Task/NewTask': RouteRecordInfo<'/Task/NewTask', '/Task/NewTask', Record<never, never>, Record<never, never>>,
  }
}
